name: Reset Commit

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Hash of the commit to be reverted'
        required: true

jobs:
  reset-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Reset to commit
        run: |
          git reset --hard ${{ github.event.inputs.commit_hash }}

      - name: Force push
        run: |
          git push --force origin HEAD:${{ github.ref_name }}
